# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by any PR against the master branch as well
# as on any push to the master branch itself
# that changes any file in gfx/UltimateCataclysm folder
name: UltimateCataclysm composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/UltimateCataclysm/**'
      - '.github/workflows/ci_build.yml'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Install Dependencies
        run: |
          apk add --no-cache musl-dev gcc vips-dev python3-dev zip py3-pip py3-wheel imagemagick
          pip3 install pyvips

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          mkdir build && cd build
          wget -q https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          cd ..
          python3 build/compose.py --use-all --obsolete-fillers gfx/UltimateCataclysm

          for file in gfx/UltimateCataclysm/*.png; do
            convert -type optimize -define png:compression-strategy=0 -define png:compression-level=9 -define png:exclude-chunk=EXIF,iCCP,iTXt,sRGB,tEXt,zCCP,zTXt,date "$file" "$file.tmp"
            original_size=$(stat -c%s "$file")
            imagemagick_size=$(stat -c%s "$file.tmp")
            if [ "$imagemagick_size" -lt "$original_size" ]; then
              echo "ImageMagick shrinked $file (${original_size} > ${imagemagick_size})"
              mv "$file.tmp" "$file"
            else
              echo "ImageMagick did not shrink $file (${original_size} <= ${imagemagick_size})"
              rm "$file.tmp"
            fi
          done

          cd build

          artifact_name=UltimateCataclysm-$(echo $GITHUB_SHA | cut -c -8)
          tileset_dir=../gfx/UltimateCataclysm

          mkdir $artifact_name
          mv $tileset_dir/*.png            $artifact_name
          mv $tileset_dir/tile_config.json $artifact_name
          mv $tileset_dir/tileset.txt      $artifact_name

          echo ::set-output name=artifact_name::$artifact_name

      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: build/${{ steps.build.outputs.artifact_name }}
