name: editorconfig conformance check

on:
  push:
    branches:
      - master
    paths:
      - '**.json'
      - '.github/workflows/editorconfig_conformance.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.json'
      - '.github/workflows/editorconfig_conformance.yml'

jobs:
  build:
    name: CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout base_ref
        run: git fetch --depth=1 origin +${{ github.base_ref }}

      - name: Verify there are no tabs in JSON and py
        id: build
        run: |
          git diff origin/${{ github.base_ref }} --name-only '*.json' '*.py' \
          | xargs -d'\n' git diff -U0 origin/${{ github.base_ref }} -- \
          | grep $'^+[^+].*\t' \
          && exit 1 \
          || exit 0
