# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by any PR against the master branch as well
# as on any push to the master branch itself
# that changes any file in gfx/HollowMoon folder
name: HollowMoon composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/HollowMoon/**'
      - '.github/workflows/hm_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/HollowMoon/**'
      - '.github/workflows/hm_build.yml'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install musl-dev gcc libvips-dev python3-dev python3-pip python3-wheel
          pip3 install pyvips

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          export TILESET="HollowMoon"
          export COMPOSE_ARGS="--use-all --obsolete-fillers"

          export BUILD_DIR="build"

          mkdir "$BUILD_DIR"
          wget -q -P "$BUILD_DIR" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          python3 "$BUILD_DIR/compose.py" $COMPOSE_ARGS "gfx/$TILESET" "$BUILD_DIR"
          cp "gfx/$TILESET/fallback.png" "$BUILD_DIR/"

          artifact_name="$TILESET-${GITHUB_SHA::7}"

          mkdir "$artifact_name"
          mv "${BUILD_DIR}"/*.png           "$artifact_name"
          mv "$BUILD_DIR/tile_config.json"  "$artifact_name"
          mv "gfx/$TILESET/tileset.txt"     "$artifact_name"

          echo ::set-output name=artifact_name::"$artifact_name"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_name }}
