# preforms CI builds using compose.py from
# https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by any PR against the master branch as well
# as on any push to the master branch itself
# that changes any file in gfx/RetroDays folder
name: RetroDays composer

on:
  push:
    branches:
      - master
    paths:
      - 'gfx/Retrodays/**'
      - '.github/workflows/Retrodays_ci_build.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'gfx/Retrodays/**'
      - '.github/workflows/Retrodays_ci_build.yml'

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt install musl-dev gcc libvips-dev python3-dev python3-pip python3-wheel
          pip3 install pyvips
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          mkdir build
          wget -q -P build https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          python3 build/compose.py --use-all gfx/Retrodays build

          artifact_name=RetroDays-${GITHUB_SHA::7}
          tileset_dir=build

          mkdir "$artifact_name"
          mv $tileset_dir/*.png              "$artifact_name"
          mv $tileset_dir/tile_config.json   "$artifact_name"
          mv gfx/Retrodays/tileset.txt       "$artifact_name"

          echo ::set-output name=artifact_name::"$artifact_name"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.artifact_name }}
          path: ${{ steps.build.outputs.artifact_name }}
